functionsDirectory = "/Users/clawdbot/before-the-data/netlify/functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []

[build]
edge_functions = "/Users/clawdbot/before-the-data/netlify/edge-functions"
publish = "/Users/clawdbot/before-the-data"
publishOrigin = "ui"
functions = "/Users/clawdbot/before-the-data/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[edge_functions]]
path = "/*"
function = "og"

[functions]

[functions."*"]

[[redirects]]
from = "/:slug"
to = "/post.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]