[functions]
  directory = "netlify/functions"

[[edge_functions]]
  path = "/og"
  function = "og"

[[edge_functions]]
  path = "/new-music"
  function = "og"

[[edge_functions]]
  path = "/post/*"
  function = "og"
